### ISSUE TITLE
nautikos-0.3.4 does not work

### ISSUE THREAD

**Issue by gbonazzoli** [janheindejong/nautikos#1]
I just tried it, but it does not work.

It seems to not find the image tag, in the deployment file.

```bash
gitlab-runner@gitlab-runner:/tmp$ nautikos fastapi-zero/ 1.2.3
Updating 'fastapi-zero/' to '1.2.3' in all environments
ERROR - Didn't find any images to modify
```
where:

```
gitlab-runner@gitlab-runner:/tmp$ cat nautikos.yaml 
environments: 
- name: prod
  manifests: 
  - path: fastapi-zero/deployment.yaml  # Path relative to configuration file
    type: kubernetes  # Type can be 'kubernetes' or 'kustomize'
```

and

```
gitlab-runner@gitlab-runner:/tmp$ cat fastapi-zero/deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-zero
  labels:
    app: fastapi-zero
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-zero
  template:
    metadata:
      labels:
        app: fastapi-zero
    spec:
      containers:
        - name: fastapi-zero
          image: reg.colombinigroup.com/fastapi-zero/fastapi-zero:3.23
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
```
